# name: 'Hello World'
# description: 'Greet someone'
# inputs:
#   testPathRegex:
#     description: 'Regex for finding tests'
#     required: false
#     default: 'tests/*.js'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
# runs:
#   using: "composite"
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Install Go
#       uses: actions/setup-go@v3
#       with:
#         go-version: 1.x
        
#     - name: Install XK6
#       run: go install go.k6.io/xk6/cmd/xk6@latest

#     - name: Cache XK6 Browser
#       id: cache-xk6-browser
#       uses: actions/cache@v3
#       with:
#         path: xk6-browser
#         key: ${{ runner.os }}-xk6-browser

#     - name: Build XK6 Browser
#       if: steps.cache-xk6-browser.outputs.cache-hit != 'true'
#       run: xk6 build --output xk6-browser --with github.com/grafana/xk6-browser

#     - name: Run E2E tests
#       run: |
#         set -x
#         export XK6_HEADLESS=true
#         for f in ${{ inputs.testPathRegex }}; do
#           ./xk6-browser run "$f"
#         done

name: 'XK6 Browser'
description: 'Run XK6 Browser tests'
inputs:
  testPathRegex:
    description: 'Regex for finding tests'
    required: false
    default: 'tests/*.js'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testPathRegex }}