name: 'XK6 Browser'
description: 'Run XK6 Browser tests'
inputs:
  include:
    description: 'Pattern to match tests'
    required: false
    value: tests/**/*.test.js
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.include }}