name: XK6 Browser
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.x

    - name: Install Go tip
      if: matrix.go == 'tip'
      run: |
        go install golang.org/dl/gotip@latest
        gotip download
        echo "GOROOT=$HOME/sdk/gotip" >> "$GITHUB_ENV"
        echo "GOPATH=$HOME/go" >> "$GITHUB_ENV"
        echo "$HOME/go/bin" >> "$GITHUB_PATH"
        echo "$HOME/sdk/gotip/bin" >> "$GITHUB_PATH"

    - name: Debug
      run: |
        pwd
        echo HOME: ${HOME}
        echo GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}
        echo GOPATH: ${GOPATH}
        echo GOROOT: ${GOROOT}

    - name: Install XK6
      run: go install go.k6.io/xk6/cmd/xk6@latest

    - name: Build extension
      run: |
        GOPRIVATE="go.k6.io/k6" xk6 build latest \
          --output ./xk6-browser \
          --with github.com/grafana/xk6-browser=.
        ./xk6-browser version

  # - name: Build XK6 Browser
  #   run: xk6 build --output xk6-browser --with github.com/grafana/xk6-browser

    # - name: Run E2E tests
    #   run: |
    #     set -x
    #     export XK6_HEADLESS=true
    #     for f in examples/*.js; do
    #       ./k6extension run "$f"
    #     done

