on: [push]

jobs:
  install_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - run: |
        go install go.k6.io/xk6/cmd/xk6@latest
        xk6 build --with github.com/grafana/xk6-browser