on: [push]

jobs:
  install_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.16.1' # The Go version to download (if necessary) and use.
    - run: go install go.k6.io/xk6/cmd/xk6@latest
    - run: xk6 build --with github.com/grafana/xk6-browser