name: example
on: [push]

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    name: Run XK6 Browser
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Build Application
        run: npm ci && npm run build

      - name: Run XK6 Browser
        uses: grafana/xk6-browser-github-action@v1
        with:
          include: tests/**/*.test.js
          app_directory: build
