on: [push]

env:
  GOPATH: /home/runner/work/github-action-basics/go

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - run: go version

      - name: Debug
        run: |
          pwd
          echo ${GOPATH}
          echo ${GOROOT}

      - name: Install XK6 Browser
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Run XK6 Browser
        run: xk6 build --output xk6-browser --with github.com/grafana/xk6-browser
