on: [push]

jobs:
  install_go:
    runs-on: ubuntu-latest
    name: Install XK6 Browser
    steps:
      - name: Install Go
        uses: actions/checkout@v3
        uses: actions/setup-go@v3
        run: go version
