name: XK6 Browser
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Install XK6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build XK6 Browser
        run: xk6 build --output xk6-browser --with github.com/grafana/xk6-browser

      - name: Run E2E tests
        run: |
          set -x
          export XK6_HEADLESS=true
          for f in tests/*.js; do
            ./xk6-browser run "$f"
          done
