on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install XK6 Browser
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
      - run: go version
